create table if not exists app.applications (
  id uuid primary key default gen_random_uuid(), owner_id uuid not null references app.profiles(id) on delete cascade, job_id uuid not null references app.jobs(id) on delete cascade, status text not null default 'draft', started_at timestamptz, applied_at timestamptz, closed_at timestamptz, current_package_id uuid, notes text, revision integer not null default 0, created_at timestamptz not null default now(), unique (owner_id, job_id)
);
create table if not exists app.application_status_history (id uuid primary key default gen_random_uuid(), application_id uuid not null references app.applications(id) on delete cascade, from_status text, to_status text not null, actor_id uuid, reason text, transitioned_at timestamptz not null default now());
create table if not exists app.application_forms (id uuid primary key default gen_random_uuid(), application_id uuid not null references app.applications(id) on delete cascade, source_url text, captured_at timestamptz not null default now(), access_method text not null, schema_version text not null, source_hash text not null, status text not null default 'captured');
create table if not exists app.application_fields (id uuid primary key default gen_random_uuid(), form_id uuid not null references app.application_forms(id) on delete cascade, sequence integer not null, label text not null, field_type text not null, required boolean not null default false, choices jsonb, char_limit integer, word_limit integer, category text, conditional_rule jsonb, sensitive boolean not null default false);
create table if not exists app.application_answer_versions (id uuid primary key default gen_random_uuid(), field_id uuid not null references app.application_fields(id) on delete cascade, version integer not null, source text not null, draft_text text not null, final_text text, limit_result jsonb, prompt_version text, model_version text, owner_edits jsonb, status text not null default 'draft', content_hash text not null, created_at timestamptz not null default now(), unique (field_id, version));
create table if not exists app.saved_answers (id uuid primary key default gen_random_uuid(), owner_id uuid not null references app.profiles(id) on delete cascade, question_category text not null, answer_version_id uuid references app.application_answer_versions(id), tags text[] not null default '{}', allowed_contexts text[] not null default '{}', source_application_id uuid references app.applications(id), last_reviewed_at timestamptz);
create table if not exists app.application_documents (id uuid primary key default gen_random_uuid(), application_id uuid not null references app.applications(id) on delete cascade, owner_id uuid not null references app.profiles(id) on delete cascade, document_kind text not null, source_type text not null, private_object_key text, source_url text, original_filename text, media_type text, byte_size bigint, content_hash text, version integer not null default 1, provenance jsonb not null default '{}', availability text not null default 'available', created_at timestamptz not null default now(), removed_at timestamptz);
